sudo: required
dist: trusty
language:
    - cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
before_script:
    # first, download and install CMake
    - export CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh"
    - wget "$CMAKE_URL"
    - sudo sh cmake-* --prefix=/usr/local --exclude-subdir
    - export PATH="/usr/local/bin:$PATH"
    - cmake --version
    
    - export CC=gcc-8
    - export CXX=g++-8
    
    # now, start build
    - mkdir build
    - cd build
    - cmake ..
    
script:
    - make
    - ./travis_test


